### ISSUE TITLE
Adapt current data loading process in c302.py to pull data from PyOpenWorm

### ISSUE THREAD

**Issue by travs** [openworm/CElegansNeuroML#27]
This data includes:
- [ ] Connectivity pattern
- [ ] Neurotransmitters
- [ ] Synaptic weights
- [ ] Neuron names

There was a start on this in #11 #12, but these are a bit out of date.

**Comment by pgleeson** [comment]
It would certainly be possible to start work on a PyOpenWormReader equivalent of [SpreadsheetDataReader.py](https://github.com/openworm/CElegansNeuroML/blob/master/CElegans/pythonScripts/SpreadsheetDataReader.py) now. Note that openworm/PyOpenWorm#152 would have to be solved before this would be replaced in c302 though. Then the neurons, (muscles), conns returned from readXFromSpreadsheet & readXFromPyOpenWorm could easily be compared.

Unfortunately the pull requests on #11 #12 are long out of date with the current version of the code so are probably best closed (thanks for your work with these @mwatts15). https://github.com/mwatts15/CElegansNeuroML/blob/master/CElegans/pythonScripts/OpenWormReader.py could be reused though...

@ahrasheed

**Comment by ahrasheed** [comment]
@travs @slarson @pgleeson 

I have made a new version of [OpenWormReader](https://github.com/ahrasheed/CElegansNeuroML/blob/master/CElegans/pythonScripts/OpenWormReader.py) in my fork of CElegansNeuroML. It is based on the code written by @mwatts15 . This version works with the latest version of PyOpenWorm. 

```python
class OpenWormReader:
    def __init__(self):
        P.connect()
        self.net = P.Worm().get_neuron_network()
        self.all_connections = self.net.synapses()

    def read(self):
        conns = []
        cells = []
        for s in self.all_connections:
            pre = str(s.pre_cell())
            post = str(s.post_cell())
            syntype = str(s.syntype())
            num = int(s.number())
            synclass = str(s.synclass())

            conns.append(ConnectionInfo(pre, post, num, syntype, synclass))

            if pre not in cells:
                cells.append(pre)
            if post not in cells:
                cells.append(post)

        print("Total cells read " + str(len(cells)))
        print("Total connections read " + str(len(conns)))
        P.disconnect()
        return cells, conns
```

The script is pretty slow because of the way it is written right now. I couldn't find (for the lack of understanding perhaps) better ways of accessing synaptic connections data from db. The reason for slow speed is that data is not loaded at once into local memory and all attributes of a connection (e.g. pre_cell, post_cell etc) are gathered by calling functions that access the database. If there is a way to load all the synaptic connection data at once into memory, that will significantly speed things up. Therefore I would really like for you guys to check the code and advise. 

There is some discrepancy in the data, which I would like to understand more about: 

1. Number of connections, which can be gathered by the following lines

     ```python
    net = P.Worm().get_neuron_network()
    self.all_connections = self.net.synapses()
    print(len(all_connections))
    ```  
 is **3225**, whereas in the [CElegansNeuronTables.xls](https://github.com/openworm/CElegansNeuroML/blob/master/CElegansNeuronTables.xls) the number of connections is **3364**. 

2. Number of unique neurons gathered through this method, is **279** whereas in the spreadsheet that number is **299** (3 neurons known to be unconnected). 

I have checked the [tests](https://github.com/openworm/PyOpenWorm/blob/master/tests/DataIntegrityTest.py#L88-L93) currently being run on PyOpenWorm and they do not address checking all synaptic connections and the number of unique neurons making those connections. Please note, this number of neurons is different from the number of neurons acquired by `self.assertEqual(302, len(set(net.neurons())))`

**Comment by travs** [comment]
@ahrasheed 
Thanks for adapting this script, I am running it locally and seeing the same issues you mention. 
This is currently the only way to get data, but you are correct, the methods can be greatly improved.
I've moved the speed issue over to openworm/PyOpenWorm#162. 

As for your points on the data discrepancy, these are due to loading from different data sources, an issue which is currently being tracked in openworm/PyOpenWorm#152

Your point about tests not running for the synaptic connections and their related neurons is also a good one, and I have raised openworm/PyOpenWorm#163

Thank you for the valuable code and comments. We should be able to add this to a pull request once we resolve openworm/PyOpenWorm#152, as @pgleeson says.

**Comment by travs** [comment]
@ahrasheed 
Hi Abdullah, it looks like openworm/PyOpenWorm#152 is very close to closing.

I think you can open a pull request on this repo now, and we'll look at next steps together upon merging.

Thanks again for the contribution!

**Comment by ahrasheed** [comment]
@travs Cool. My only concern would be that use of the script to load data from PyOpenWorm, would be impractical until the two issues you recently opened ([this](https://github.com/openworm/PyOpenWorm/issues/162) and [this](https://github.com/openworm/PyOpenWorm/issues/163)) are resolved. However, since I am not replacing the data loading mechanism in c302 just yet, I think they can also be resolved in parallel before data loading mechanisms in c302 are permanently changed from spreadsheet reading to loading from PyOpenWorm. Therefore, I ll recommend keeping this issue open till then.

**Comment by travs** [comment]
@ahrasheed 
I agree; let's leave this open until those are resolved.

Regarding your second point, I had a look at NeuronConnect.xls in excel ([using the first method here](https://support.office.com/en-sg/article/Count-unique-values-among-duplicates-8d9a69b3-b867-490e-82e0-a929fbc1e273)) and I am calculating **280** unique neurons making connections, further highlighting the need for https://github.com/openworm/PyOpenWorm/issues/163.

Does the **299** you are referencing come from CElegansNeuronTables.xls perhaps?

**Comment by ahrasheed** [comment]
@travs yes, that is correct. There are **299** connected cells in CElegansNeuronTables.xls and there **3** known unconnected neurons.

**Comment by travs** [comment]
@ahrasheed 
Ok right. I've mentioned you in the gitter chat to have a more fine-grained discussion about this.

The differing data sources problem is actually being tracked over in https://github.com/openworm/PyOpenWorm/issues/152, so anything that comes out of our chat let's raise over there.

**Comment by slarson** [comment]
@stevenjcook Can you have a look at this?  This will become moot as we are also integrating your new data spreadsheet openworm/PyOpenWorm#168 but for historical purposes, we are confused as to why [the spreadsheet](http://www.wormatlas.org/images/NeuronConnect.xls) [on WormAtlas](http://www.wormatlas.org/neuronalwiring.html) Seems to only have ~279-280 connected neurons instead of 299?  It looks like your new data spreadsheet also has 299 as we would have expected.

**Comment by travs** [comment]
We now have OpenWormReader now, from #46, but c302 is not using it anywhere, so I made #49 to capture this.

**Comment by slarson** [comment]
OK; so now we've got [a release to master](https://github.com/openworm/PyOpenWorm/releases/tag/v0.6.0) of PyOpenWorm

So folks who have been waiting on this one maybe now we can get back to it.  @ahrasheed are you up for it?  There is also commentary over on #49 but these are starting to look increasingly duplicate....

**Comment by Jueast** [comment]
Hi, I'm trying to modify OpenWormReader.py and c302.py to pull the data from PyOpenWorm in my fork. As a result, they seem to work well jointly in my laptop.( but it takes extremely long time!:( ) [Here](https://github.com/Jueast/CElegansNeuroML/blob/master/CElegans/pythonScripts/OpenWormReader.py) you can view my OpenWormReader.py. 

To make this script, I read SpreadsheetDataReader.py for reference. Although they two are equivalent in functions, their speed differs greatly! I notice that you have an issue about speed: openworm/PyOpenWorm#163, but it's still open. Maybe I will try it later. Is there any other solution ? 

And I'd like to understand more how you check the correctness of these scripts, should I add some unit tests?

**Comment by pgleeson** [comment]
@Jueast thanks for the updates. Yes, OpenWormReader is much slower than the SpreadsheetDataReader, see here: https://github.com/openworm/CElegansNeuroML/issues/49.

This needs to be solved in PyOpenWorm before OpenWormReader is a viable alternative for loading the connectome in c302. See https://github.com/openworm/PyOpenWorm/issues/90

**Comment by slarson** [comment]
@pgleeson Hello -- now with #90 greatly improved, can we give this another go?  🍻

**Comment by pgleeson** [comment]
It would be nice, but 25 sec every time c302 generates a new network is still a bit too much... 

UpdatedSpreadsheetDataReader.py by @lungd is much faster, and *should* contain the same data as PyOpenWorm (i.e. [herm_full_edgelist.csv](https://github.com/openworm/CElegansNeuroML/blob/master/herm_full_edgelist.csv))... This needs to be checked though...

**Comment by slarson** [comment]
@mwatts15 @pgleeson Proposal.  What if we write a script that updates the spreadsheet out of PyOpenWorm, decoupled from the c302 network generation?

**Comment by mwatts15** [comment]
Closing this since the relevant code has moved to c302. Relevant issue openworm/c302#10
